import { ICountry } from "./types.ts"

export const isoCountries: ICountry[] = [
  {
    countryCode: "AF",
    countryName: "Afghanistan",
    alpha3Code: "AFG",
    numericCode: "004",
  },
  {
    countryCode: "AX",
    countryName: "Åland Islands",
    alpha3Code: "ALA",
    numericCode: "248",
    alternativeNames: ["Aland Islands"],
  },
  {
    countryCode: "AL",
    countryName: "Albania",
    alpha3Code: "ALB",
    numericCode: "008",
  },
  {
    countryCode: "DZ",
    countryName: "Algeria",
    alpha3Code: "DZA",
    numericCode: "012",
  },
  {
    countryCode: "AS",
    countryName: "American Samoa",
    alpha3Code: "ASM",
    numericCode: "016",
  },
  {
    countryCode: "AD",
    countryName: "Andorra",
    alpha3Code: "AND",
    numericCode: "020",
  },
  {
    countryCode: "AO",
    countryName: "Angola",
    alpha3Code: "AGO",
    numericCode: "024",
  },
  {
    countryCode: "AI",
    countryName: "Anguilla",
    alpha3Code: "AIA",
    numericCode: "660",
  },
  {
    countryCode: "AQ",
    countryName: "Antarctica",
    alpha3Code: "ATA",
    numericCode: "010",
  },
  {
    countryCode: "AG",
    countryName: "Antigua and Barbuda",
    alpha3Code: "ATG",
    numericCode: "028",
  },
  {
    countryCode: "AR",
    countryName: "Argentina",
    alpha3Code: "ARG",
    numericCode: "032",
  },
  {
    countryCode: "AM",
    countryName: "Armenia",
    alpha3Code: "ARM",
    numericCode: "051",
  },
  {
    countryCode: "AW",
    countryName: "Aruba",
    alpha3Code: "ABW",
    numericCode: "533",
  },
  {
    countryCode: "AU",
    countryName: "Australia",
    alpha3Code: "AUS",
    numericCode: "036",
  },
  {
    countryCode: "AT",
    countryName: "Austria",
    alpha3Code: "AUT",
    numericCode: "040",
  },
  {
    countryCode: "AZ",
    countryName: "Azerbaijan",
    alpha3Code: "AZE",
    numericCode: "031",
  },
  {
    countryCode: "BS",
    countryName: "Bahamas (the)",
    alpha3Code: "BHS",
    numericCode: "044",
    alternativeNames: ["Bahamas"],
  },
  {
    countryCode: "BH",
    countryName: "Bahrain",
    alpha3Code: "BHR",
    numericCode: "048",
  },
  {
    countryCode: "BD",
    countryName: "Bangladesh",
    alpha3Code: "BGD",
    numericCode: "050",
  },
  {
    countryCode: "BB",
    countryName: "Barbados",
    alpha3Code: "BRB",
    numericCode: "052",
  },
  {
    countryCode: "BY",
    countryName: "Belarus",
    alpha3Code: "BLR",
    numericCode: "112",
  },
  {
    countryCode: "BE",
    countryName: "Belgium",
    alpha3Code: "BEL",
    numericCode: "056",
  },
  {
    countryCode: "BZ",
    countryName: "Belize",
    alpha3Code: "BLZ",
    numericCode: "084",
  },
  {
    countryCode: "BJ",
    countryName: "Benin",
    alpha3Code: "BEN",
    numericCode: "204",
  },
  {
    countryCode: "BM",
    countryName: "Bermuda",
    alpha3Code: "BMU",
    numericCode: "060",
  },
  {
    countryCode: "BT",
    countryName: "Bhutan",
    alpha3Code: "BTN",
    numericCode: "064",
  },
  {
    countryCode: "BO",
    countryName: "Bolivia (Plurinational State of)",
    alpha3Code: "BOL",
    numericCode: "068",
    alternativeNames: ["Bolivia"],
  },
  {
    countryCode: "BQ",
    countryName: "Bonaire, Sint Eustatius and Saba",
    alpha3Code: "BES",
    numericCode: "535",
  },
  {
    countryCode: "BA",
    countryName: "Bosnia and Herzegovina",
    alpha3Code: "BIH",
    numericCode: "070",
  },
  {
    countryCode: "BW",
    countryName: "Botswana",
    alpha3Code: "BWA",
    numericCode: "072",
  },
  {
    countryCode: "BV",
    countryName: "Bouvet Island",
    alpha3Code: "BVT",
    numericCode: "074",
  },
  {
    countryCode: "BR",
    countryName: "Brazil",
    alpha3Code: "BRA",
    numericCode: "076",
  },
  {
    countryCode: "IO",
    countryName: "British Indian Ocean Territory (the)",
    alpha3Code: "IOT",
    numericCode: "086",
    alternativeNames: ["British Indian Ocean Territory"],
  },
  {
    countryCode: "BN",
    countryName: "Brunei Darussalam",
    alpha3Code: "BRN",
    numericCode: "096",
    alternativeNames: ["Brunei"],
  },
  {
    countryCode: "BG",
    countryName: "Bulgaria",
    alpha3Code: "BGR",
    numericCode: "100",
  },
  {
    countryCode: "BF",
    countryName: "Burkina Faso",
    alpha3Code: "BFA",
    numericCode: "854",
  },
  {
    countryCode: "BI",
    countryName: "Burundi",
    alpha3Code: "BDI",
    numericCode: "108",
  },
  {
    countryCode: "CV",
    countryName: "Cabo Verde",
    alpha3Code: "CPV",
    numericCode: "132",
    alternativeNames: ["Cape Verde"],
  },
  {
    countryCode: "KH",
    countryName: "Cambodia",
    alpha3Code: "KHM",
    numericCode: "116",
  },
  {
    countryCode: "CM",
    countryName: "Cameroon",
    alpha3Code: "CMR",
    numericCode: "120",
  },
  {
    countryCode: "CA",
    countryName: "Canada",
    alpha3Code: "CAN",
    numericCode: "124",
  },
  {
    countryCode: "KY",
    countryName: "Cayman Islands (the)",
    alpha3Code: "CYM",
    numericCode: "136",
    alternativeNames: ["Cayman Islands"],
  },
  {
    countryCode: "CF",
    countryName: "Central African Republic (the)",
    alpha3Code: "CAF",
    numericCode: "140",
    alternativeNames: ["Central African Republic"],
  },
  {
    countryCode: "TD",
    countryName: "Chad",
    alpha3Code: "TCD",
    numericCode: "148",
  },
  {
    countryCode: "CL",
    countryName: "Chile",
    alpha3Code: "CHL",
    numericCode: "152",
  },
  {
    countryCode: "CN",
    countryName: "China",
    alpha3Code: "CHN",
    numericCode: "156",
  },
  {
    countryCode: "CX",
    countryName: "Christmas Island",
    alpha3Code: "CXR",
    numericCode: "162",
  },
  {
    countryCode: "CC",
    countryName: "Cocos (Keeling) Islands (the)",
    alpha3Code: "CCK",
    numericCode: "166",
    alternativeNames: ["Cocos (Keeling) Islands"],
  },
  {
    countryCode: "CO",
    countryName: "Colombia",
    alpha3Code: "COL",
    numericCode: "170",
  },
  {
    countryCode: "KM",
    countryName: "Comoros (the)",
    alpha3Code: "COM",
    numericCode: "174",
    alternativeNames: ["Comoros"],
  },
  {
    countryCode: "CD",
    countryName: "Congo (the Democratic Republic of the)",
    alpha3Code: "COD",
    numericCode: "180",
    alternativeNames: [
      "Congo, Democratic Republic",
      "Democratic Republic of Congo",
      "Democratic Republic of the Congo",
      "Congo (Kinshasa)",
    ],
  },
  {
    countryCode: "CG",
    countryName: "Congo (the)",
    alpha3Code: "COG",
    numericCode: "178",
    alternativeNames: ["Congo", "Congo (Brazzaville)"],
  },
  {
    countryCode: "CK",
    countryName: "Cook Islands (the)",
    alpha3Code: "COK",
    numericCode: "184",
    alternativeNames: ["Cook Islands"],
  },
  {
    countryCode: "CR",
    countryName: "Costa Rica",
    alpha3Code: "CRI",
    numericCode: "188",
  },
  {
    countryCode: "CI",
    countryName: "Côte d'Ivoire",
    alpha3Code: "CIV",
    numericCode: "384",
    alternativeNames: ["Cote d'Ivoire", "Ivory Coast"],
  },
  {
    countryCode: "HR",
    countryName: "Croatia",
    alpha3Code: "HRV",
    numericCode: "191",
  },
  {
    countryCode: "CU",
    countryName: "Cuba",
    alpha3Code: "CUB",
    numericCode: "192",
  },
  {
    countryCode: "CW",
    countryName: "Curaçao",
    alpha3Code: "CUW",
    numericCode: "531",
    alternativeNames: ["Curacao"],
  },
  {
    countryCode: "CY",
    countryName: "Cyprus",
    alpha3Code: "CYP",
    numericCode: "196",
  },
  {
    countryCode: "CZ",
    countryName: "Czechia",
    alpha3Code: "CZE",
    numericCode: "203",
    alternativeNames: ["Czech Republic"],
  },
  {
    countryCode: "DK",
    countryName: "Denmark",
    alpha3Code: "DNK",
    numericCode: "208",
  },
  {
    countryCode: "DJ",
    countryName: "Djibouti",
    alpha3Code: "DJI",
    numericCode: "262",
  },
  {
    countryCode: "DM",
    countryName: "Dominica",
    alpha3Code: "DMA",
    numericCode: "212",
  },
  {
    countryCode: "DO",
    countryName: "Dominican Republic (the)",
    alpha3Code: "DOM",
    numericCode: "214",
    alternativeNames: ["Dominican Republic"],
  },
  {
    countryCode: "EC",
    countryName: "Ecuador",
    alpha3Code: "ECU",
    numericCode: "218",
  },
  {
    countryCode: "EG",
    countryName: "Egypt",
    alpha3Code: "EGY",
    numericCode: "818",
  },
  {
    countryCode: "SV",
    countryName: "El Salvador",
    alpha3Code: "SLV",
    numericCode: "222",
  },
  {
    countryCode: "GQ",
    countryName: "Equatorial Guinea",
    alpha3Code: "GNQ",
    numericCode: "226",
  },
  {
    countryCode: "ER",
    countryName: "Eritrea",
    alpha3Code: "ERI",
    numericCode: "232",
  },
  {
    countryCode: "EE",
    countryName: "Estonia",
    alpha3Code: "EST",
    numericCode: "233",
  },
  {
    countryCode: "SZ",
    countryName: "Eswatini",
    alpha3Code: "SWZ",
    numericCode: "748",
    alternativeNames: ["Swaziland"],
  },
  {
    countryCode: "ET",
    countryName: "Ethiopia",
    alpha3Code: "ETH",
    numericCode: "231",
  },
  {
    countryCode: "FK",
    countryName: "Falkland Islands (the) [Malvinas]",
    alpha3Code: "FLK",
    numericCode: "238",
    alternativeNames: ["Falkland Islands (Malvinas)", "Falkland Islands"],
  },
  {
    countryCode: "FO",
    countryName: "Faroe Islands (the)",
    alpha3Code: "FRO",
    numericCode: "234",
    alternativeNames: ["Faroe Islands", "Faeroe Islands"],
  },
  {
    countryCode: "FJ",
    countryName: "Fiji",
    alpha3Code: "FJI",
    numericCode: "242",
  },
  {
    countryCode: "FI",
    countryName: "Finland",
    alpha3Code: "FIN",
    numericCode: "246",
  },
  {
    countryCode: "FR",
    countryName: "France",
    alpha3Code: "FRA",
    numericCode: "250",
  },
  {
    countryCode: "GF",
    countryName: "French Guiana",
    alpha3Code: "GUF",
    numericCode: "254",
  },
  {
    countryCode: "PF",
    countryName: "French Polynesia",
    alpha3Code: "PYF",
    numericCode: "258",
  },
  {
    countryCode: "TF",
    countryName: "French Southern Territories (the)",
    alpha3Code: "ATF",
    numericCode: "260",
    alternativeNames: ["French Southern Territories"],
  },
  {
    countryCode: "GA",
    countryName: "Gabon",
    alpha3Code: "GAB",
    numericCode: "266",
  },
  {
    countryCode: "GM",
    countryName: "Gambia (the)",
    alpha3Code: "GMB",
    numericCode: "270",
    alternativeNames: ["Gambia"],
  },
  {
    countryCode: "GE",
    countryName: "Georgia",
    alpha3Code: "GEO",
    numericCode: "268",
  },
  {
    countryCode: "DE",
    countryName: "Germany",
    alpha3Code: "DEU",
    numericCode: "276",
  },
  {
    countryCode: "GH",
    countryName: "Ghana",
    alpha3Code: "GHA",
    numericCode: "288",
  },
  {
    countryCode: "GI",
    countryName: "Gibraltar",
    alpha3Code: "GIB",
    numericCode: "292",
  },
  {
    countryCode: "GR",
    countryName: "Greece",
    alpha3Code: "GRC",
    numericCode: "300",
  },
  {
    countryCode: "GL",
    countryName: "Greenland",
    alpha3Code: "GRL",
    numericCode: "304",
  },
  {
    countryCode: "GD",
    countryName: "Grenada",
    alpha3Code: "GRD",
    numericCode: "308",
  },
  {
    countryCode: "GP",
    countryName: "Guadeloupe",
    alpha3Code: "GLP",
    numericCode: "312",
  },
  {
    countryCode: "GU",
    countryName: "Guam",
    alpha3Code: "GUM",
    numericCode: "316",
  },
  {
    countryCode: "GT",
    countryName: "Guatemala",
    alpha3Code: "GTM",
    numericCode: "320",
  },
  {
    countryCode: "GG",
    countryName: "Guernsey",
    alpha3Code: "GGY",
    numericCode: "831",
  },
  {
    countryCode: "GN",
    countryName: "Guinea",
    alpha3Code: "GIN",
    numericCode: "324",
  },
  {
    countryCode: "GW",
    countryName: "Guinea-Bissau",
    alpha3Code: "GNB",
    numericCode: "624",
  },
  {
    countryCode: "GY",
    countryName: "Guyana",
    alpha3Code: "GUY",
    numericCode: "328",
  },
  {
    countryCode: "HT",
    countryName: "Haiti",
    alpha3Code: "HTI",
    numericCode: "332",
  },
  {
    countryCode: "HM",
    countryName: "Heard Island and McDonald Islands",
    alpha3Code: "HMD",
    numericCode: "334",
  },
  {
    countryCode: "VA",
    countryName: "Holy See (the)",
    alpha3Code: "VAT",
    numericCode: "336",
    alternativeNames: [
      "Holy See",
      "Holy See (Vatican City State)",
      "Vatican",
      "Vatican City",
    ],
  },
  {
    countryCode: "HN",
    countryName: "Honduras",
    alpha3Code: "HND",
    numericCode: "340",
  },
  {
    countryCode: "HK",
    countryName: "Hong Kong",
    alpha3Code: "HKG",
    numericCode: "344",
  },
  {
    countryCode: "HU",
    countryName: "Hungary",
    alpha3Code: "HUN",
    numericCode: "348",
  },
  {
    countryCode: "IS",
    countryName: "Iceland",
    alpha3Code: "ISL",
    numericCode: "352",
  },
  {
    countryCode: "IN",
    countryName: "India",
    alpha3Code: "IND",
    numericCode: "356",
  },
  {
    countryCode: "ID",
    countryName: "Indonesia",
    alpha3Code: "IDN",
    numericCode: "360",
  },
  {
    countryCode: "IR",
    countryName: "Iran (Islamic Republic of)",
    alpha3Code: "IRN",
    numericCode: "364",
    alternativeNames: ["Iran"],
  },
  {
    countryCode: "IQ",
    countryName: "Iraq",
    alpha3Code: "IRQ",
    numericCode: "368",
  },
  {
    countryCode: "IE",
    countryName: "Ireland",
    alpha3Code: "IRL",
    numericCode: "372",
  },
  {
    countryCode: "IM",
    countryName: "Isle of Man",
    alpha3Code: "IMN",
    numericCode: "833",
  },
  {
    countryCode: "IL",
    countryName: "Israel",
    alpha3Code: "ISR",
    numericCode: "376",
  },
  {
    countryCode: "IT",
    countryName: "Italy",
    alpha3Code: "ITA",
    numericCode: "380",
  },
  {
    countryCode: "JM",
    countryName: "Jamaica",
    alpha3Code: "JAM",
    numericCode: "388",
  },
  {
    countryCode: "JP",
    countryName: "Japan",
    alpha3Code: "JPN",
    numericCode: "392",
  },
  {
    countryCode: "JE",
    countryName: "Jersey",
    alpha3Code: "JEY",
    numericCode: "832",
  },
  {
    countryCode: "JO",
    countryName: "Jordan",
    alpha3Code: "JOR",
    numericCode: "400",
  },
  {
    countryCode: "KZ",
    countryName: "Kazakhstan",
    alpha3Code: "KAZ",
    numericCode: "398",
  },
  {
    countryCode: "KE",
    countryName: "Kenya",
    alpha3Code: "KEN",
    numericCode: "404",
  },
  {
    countryCode: "KI",
    countryName: "Kiribati",
    alpha3Code: "KIR",
    numericCode: "296",
  },
  {
    countryCode: "KP",
    countryName: "Korea (the Democratic People's Republic of)",
    alpha3Code: "PRK",
    numericCode: "408",
    alternativeNames: ["North Korea"],
  },
  {
    countryCode: "KR",
    countryName: "Korea (the Republic of)",
    alpha3Code: "KOR",
    numericCode: "410",
    alternativeNames: ["Korea", "South Korea"],
  },
  {
    countryCode: "KW",
    countryName: "Kuwait",
    alpha3Code: "KWT",
    numericCode: "414",
  },
  {
    countryCode: "KG",
    countryName: "Kyrgyzstan",
    alpha3Code: "KGZ",
    numericCode: "417",
  },
  {
    countryCode: "LA",
    countryName: "Lao People's Democratic Republic (the)",
    alpha3Code: "LAO",
    numericCode: "418",
    alternativeNames: ["Laos", "Lao People's Democratic Republic"],
  },
  {
    countryCode: "LV",
    countryName: "Latvia",
    alpha3Code: "LVA",
    numericCode: "428",
  },
  {
    countryCode: "LB",
    countryName: "Lebanon",
    alpha3Code: "LBN",
    numericCode: "422",
  },
  {
    countryCode: "LS",
    countryName: "Lesotho",
    alpha3Code: "LSO",
    numericCode: "426",
  },
  {
    countryCode: "LR",
    countryName: "Liberia",
    alpha3Code: "LBR",
    numericCode: "430",
  },
  {
    countryCode: "LY",
    countryName: "Libya",
    alpha3Code: "LBY",
    numericCode: "434",
  },
  {
    countryCode: "LI",
    countryName: "Liechtenstein",
    alpha3Code: "LIE",
    numericCode: "438",
  },
  {
    countryCode: "LT",
    countryName: "Lithuania",
    alpha3Code: "LTU",
    numericCode: "440",
  },
  {
    countryCode: "LU",
    countryName: "Luxembourg",
    alpha3Code: "LUX",
    numericCode: "442",
  },
  {
    countryCode: "MO",
    countryName: "Macao",
    alpha3Code: "MAC",
    numericCode: "446",
  },
  {
    countryCode: "MG",
    countryName: "Madagascar",
    alpha3Code: "MDG",
    numericCode: "450",
  },
  {
    countryCode: "MW",
    countryName: "Malawi",
    alpha3Code: "MWI",
    numericCode: "454",
  },
  {
    countryCode: "MY",
    countryName: "Malaysia",
    alpha3Code: "MYS",
    numericCode: "458",
  },
  {
    countryCode: "MV",
    countryName: "Maldives",
    alpha3Code: "MDV",
    numericCode: "462",
  },
  {
    countryCode: "ML",
    countryName: "Mali",
    alpha3Code: "MLI",
    numericCode: "466",
  },
  {
    countryCode: "MT",
    countryName: "Malta",
    alpha3Code: "MLT",
    numericCode: "470",
  },
  {
    countryCode: "MH",
    countryName: "Marshall Islands (the)",
    alpha3Code: "MHL",
    numericCode: "584",
    alternativeNames: ["Marshall Islands"],
  },
  {
    countryCode: "MQ",
    countryName: "Martinique",
    alpha3Code: "MTQ",
    numericCode: "474",
  },
  {
    countryCode: "MR",
    countryName: "Mauritania",
    alpha3Code: "MRT",
    numericCode: "478",
  },
  {
    countryCode: "MU",
    countryName: "Mauritius",
    alpha3Code: "MUS",
    numericCode: "480",
  },
  {
    countryCode: "YT",
    countryName: "Mayotte",
    alpha3Code: "MYT",
    numericCode: "175",
  },
  {
    countryCode: "MX",
    countryName: "Mexico",
    alpha3Code: "MEX",
    numericCode: "484",
  },
  {
    countryCode: "FM",
    countryName: "Micronesia (Federated States of)",
    alpha3Code: "FSM",
    numericCode: "583",
  },
  {
    countryCode: "MD",
    countryName: "Moldova (the Republic of)",
    alpha3Code: "MDA",
    numericCode: "498",
    alternativeNames: ["Moldova", "Republic of Moldova"],
  },
  {
    countryCode: "MC",
    countryName: "Monaco",
    alpha3Code: "MCO",
    numericCode: "492",
  },
  {
    countryCode: "MN",
    countryName: "Mongolia",
    alpha3Code: "MNG",
    numericCode: "496",
  },
  {
    countryCode: "ME",
    countryName: "Montenegro",
    alpha3Code: "MNE",
    numericCode: "499",
  },
  {
    countryCode: "MS",
    countryName: "Montserrat",
    alpha3Code: "MSR",
    numericCode: "500",
  },
  {
    countryCode: "MA",
    countryName: "Morocco",
    alpha3Code: "MAR",
    numericCode: "504",
  },
  {
    countryCode: "MZ",
    countryName: "Mozambique",
    alpha3Code: "MOZ",
    numericCode: "508",
  },
  {
    countryCode: "MM",
    countryName: "Myanmar",
    alpha3Code: "MMR",
    numericCode: "104",
  },
  {
    countryCode: "NA",
    countryName: "Namibia",
    alpha3Code: "NAM",
    numericCode: "516",
  },
  {
    countryCode: "NR",
    countryName: "Nauru",
    alpha3Code: "NRU",
    numericCode: "520",
  },
  {
    countryCode: "NP",
    countryName: "Nepal",
    alpha3Code: "NPL",
    numericCode: "524",
  },
  {
    countryCode: "NL",
    countryName: "Netherlands (the)",
    alpha3Code: "NLD",
    numericCode: "528",
    alternativeNames: ["Netherlands"],
  },
  {
    countryCode: "NC",
    countryName: "New Caledonia",
    alpha3Code: "NCL",
    numericCode: "540",
  },
  {
    countryCode: "NZ",
    countryName: "New Zealand",
    alpha3Code: "NZL",
    numericCode: "554",
  },
  {
    countryCode: "NI",
    countryName: "Nicaragua",
    alpha3Code: "NIC",
    numericCode: "558",
  },
  {
    countryCode: "NE",
    countryName: "Niger (the)",
    alpha3Code: "NER",
    numericCode: "562",
    alternativeNames: ["Niger"],
  },
  {
    countryCode: "NG",
    countryName: "Nigeria",
    alpha3Code: "NGA",
    numericCode: "566",
  },
  {
    countryCode: "NU",
    countryName: "Niue",
    alpha3Code: "NIU",
    numericCode: "570",
  },
  {
    countryCode: "NF",
    countryName: "Norfolk Island",
    alpha3Code: "NFK",
    numericCode: "574",
  },
  {
    countryCode: "MK",
    countryName: "North Macedonia",
    alpha3Code: "MKD",
    numericCode: "807",
    alternativeNames: [
      "Macedonia",
      "The former Yugoslav Republic of Macedonia",
    ],
  },
  {
    countryCode: "MP",
    countryName: "Northern Mariana Islands (the)",
    alpha3Code: "MNP",
    numericCode: "580",
    alternativeNames: ["Northern Mariana Islands"],
  },
  {
    countryCode: "NO",
    countryName: "Norway",
    alpha3Code: "NOR",
    numericCode: "578",
  },
  {
    countryCode: "OM",
    countryName: "Oman",
    alpha3Code: "OMN",
    numericCode: "512",
  },
  {
    countryCode: "PK",
    countryName: "Pakistan",
    alpha3Code: "PAK",
    numericCode: "586",
  },
  {
    countryCode: "PW",
    countryName: "Palau",
    alpha3Code: "PLW",
    numericCode: "585",
  },
  {
    countryCode: "PS",
    countryName: "Palestine, State of",
    alpha3Code: "PSE",
    numericCode: "275",
    alternativeNames: ["Palestine", "State of Palestine"],
  },
  {
    countryCode: "PA",
    countryName: "Panama",
    alpha3Code: "PAN",
    numericCode: "591",
  },
  {
    countryCode: "PG",
    countryName: "Papua New Guinea",
    alpha3Code: "PNG",
    numericCode: "598",
  },
  {
    countryCode: "PY",
    countryName: "Paraguay",
    alpha3Code: "PRY",
    numericCode: "600",
  },
  {
    countryCode: "PE",
    countryName: "Peru",
    alpha3Code: "PER",
    numericCode: "604",
  },
  {
    countryCode: "PH",
    countryName: "Philippines (the)",
    alpha3Code: "PHL",
    numericCode: "608",
    alternativeNames: ["Philippines"],
  },
  {
    countryCode: "PN",
    countryName: "Pitcairn",
    alpha3Code: "PCN",
    numericCode: "612",
    alternativeNames: ["Pitcairn Islands"],
  },
  {
    countryCode: "PL",
    countryName: "Poland",
    alpha3Code: "POL",
    numericCode: "616",
  },
  {
    countryCode: "PT",
    countryName: "Portugal",
    alpha3Code: "PRT",
    numericCode: "620",
  },
  {
    countryCode: "PR",
    countryName: "Puerto Rico",
    alpha3Code: "PRI",
    numericCode: "630",
  },
  {
    countryCode: "QA",
    countryName: "Qatar",
    alpha3Code: "QAT",
    numericCode: "634",
  },
  {
    countryCode: "RE",
    countryName: "Réunion",
    alpha3Code: "REU",
    numericCode: "638",
    alternativeNames: ["Reunion"],
  },
  {
    countryCode: "RO",
    countryName: "Romania",
    alpha3Code: "ROU",
    numericCode: "642",
  },
  {
    countryCode: "RU",
    countryName: "Russian Federation (the)",
    alpha3Code: "RUS",
    numericCode: "643",
    alternativeNames: ["Russian Federation", "Russia"],
  },
  {
    countryCode: "RW",
    countryName: "Rwanda",
    alpha3Code: "RWA",
    numericCode: "646",
  },
  {
    countryCode: "BL",
    countryName: "Saint Barthélemy",
    alpha3Code: "BLM",
    numericCode: "652",
    alternativeNames: ["Saint Barthelemy", "St. Barths", "St. Barts"],
  },
  {
    countryCode: "SH",
    countryName: "Saint Helena, Ascension and Tristan da Cunha",
    alpha3Code: "SHN",
    numericCode: "654",
    alternativeNames: ["Saint Helena"],
  },
  {
    countryCode: "KN",
    countryName: "Saint Kitts and Nevis",
    alpha3Code: "KNA",
    numericCode: "659",
  },
  {
    countryCode: "LC",
    countryName: "Saint Lucia",
    alpha3Code: "LCA",
    numericCode: "662",
  },
  {
    countryCode: "MF",
    countryName: "Saint Martin (French part)",
    alpha3Code: "MAF",
    numericCode: "663",
    alternativeNames: ["Saint Martin"],
  },
  {
    countryCode: "PM",
    countryName: "Saint Pierre and Miquelon",
    alpha3Code: "SPM",
    numericCode: "666",
  },
  {
    countryCode: "VC",
    countryName: "Saint Vincent and the Grenadines",
    alpha3Code: "VCT",
    numericCode: "670",
    alternativeNames: ["Saint Vincent"],
  },
  {
    countryCode: "WS",
    countryName: "Samoa",
    alpha3Code: "WSM",
    numericCode: "882",
  },
  {
    countryCode: "SM",
    countryName: "San Marino",
    alpha3Code: "SMR",
    numericCode: "674",
  },
  {
    countryCode: "ST",
    countryName: "Sao Tome and Principe",
    alpha3Code: "STP",
    numericCode: "678",
  },
  {
    countryCode: "SA",
    countryName: "Saudi Arabia",
    alpha3Code: "SAU",
    numericCode: "682",
  },
  {
    countryCode: "SN",
    countryName: "Senegal",
    alpha3Code: "SEN",
    numericCode: "686",
  },
  {
    countryCode: "RS",
    countryName: "Serbia",
    alpha3Code: "SRB",
    numericCode: "688",
  },
  {
    countryCode: "SC",
    countryName: "Seychelles",
    alpha3Code: "SYC",
    numericCode: "690",
  },
  {
    countryCode: "SL",
    countryName: "Sierra Leone",
    alpha3Code: "SLE",
    numericCode: "694",
  },
  {
    countryCode: "SG",
    countryName: "Singapore",
    alpha3Code: "SGP",
    numericCode: "702",
  },
  {
    countryCode: "SX",
    countryName: "Sint Maarten (Dutch part)",
    alpha3Code: "SXM",
    numericCode: "534",
    alternativeNames: ["Sint Maarten"],
  },
  {
    countryCode: "SK",
    countryName: "Slovakia",
    alpha3Code: "SVK",
    numericCode: "703",
  },
  {
    countryCode: "SI",
    countryName: "Slovenia",
    alpha3Code: "SVN",
    numericCode: "705",
  },
  {
    countryCode: "SB",
    countryName: "Solomon Islands",
    alpha3Code: "SLB",
    numericCode: "090",
  },
  {
    countryCode: "SO",
    countryName: "Somalia",
    alpha3Code: "SOM",
    numericCode: "706",
  },
  {
    countryCode: "ZA",
    countryName: "South Africa",
    alpha3Code: "ZAF",
    numericCode: "710",
  },
  {
    countryCode: "GS",
    countryName: "South Georgia and the South Sandwich Islands",
    alpha3Code: "SGS",
    numericCode: "239",
  },
  {
    countryCode: "SS",
    countryName: "South Sudan",
    alpha3Code: "SSD",
    numericCode: "728",
  },
  {
    countryCode: "ES",
    countryName: "Spain",
    alpha3Code: "ESP",
    numericCode: "724",
  },
  {
    countryCode: "LK",
    countryName: "Sri Lanka",
    alpha3Code: "LKA",
    numericCode: "144",
  },
  {
    countryCode: "SD",
    countryName: "Sudan (the)",
    alpha3Code: "SDN",
    numericCode: "729",
    alternativeNames: ["Sudan"],
  },
  {
    countryCode: "SR",
    countryName: "Suriname",
    alpha3Code: "SUR",
    numericCode: "740",
  },
  {
    countryCode: "SJ",
    countryName: "Svalbard and Jan Mayen",
    alpha3Code: "SJM",
    numericCode: "744",
  },
  {
    countryCode: "SE",
    countryName: "Sweden",
    alpha3Code: "SWE",
    numericCode: "752",
  },
  {
    countryCode: "CH",
    countryName: "Switzerland",
    alpha3Code: "CHE",
    numericCode: "756",
  },
  {
    countryCode: "SY",
    countryName: "Syrian Arab Republic (the)",
    alpha3Code: "SYR",
    numericCode: "760",
    alternativeNames: ["Syrian Arab Republic", "Syria"],
  },
  {
    countryCode: "TW",
    countryName: "Taiwan (Province of China)",
    alpha3Code: "TWN",
    numericCode: "158",
    alternativeNames: ["Taiwan"],
  },
  {
    countryCode: "TJ",
    countryName: "Tajikistan",
    alpha3Code: "TJK",
    numericCode: "762",
  },
  {
    countryCode: "TZ",
    countryName: "Tanzania, the United Republic of",
    alpha3Code: "TZA",
    numericCode: "834",
    alternativeNames: ["Tanzania", "United Republic of Tanzania"],
  },
  {
    countryCode: "TH",
    countryName: "Thailand",
    alpha3Code: "THA",
    numericCode: "764",
  },
  {
    countryCode: "TL",
    countryName: "Timor-Leste",
    alpha3Code: "TLS",
    numericCode: "626",
    alternativeNames: ["East Timor", "Timor"],
  },
  {
    countryCode: "TG",
    countryName: "Togo",
    alpha3Code: "TGO",
    numericCode: "768",
  },
  {
    countryCode: "TK",
    countryName: "Tokelau",
    alpha3Code: "TKL",
    numericCode: "772",
  },
  {
    countryCode: "TO",
    countryName: "Tonga",
    alpha3Code: "TON",
    numericCode: "776",
  },
  {
    countryCode: "TT",
    countryName: "Trinidad and Tobago",
    alpha3Code: "TTO",
    numericCode: "780",
  },
  {
    countryCode: "TN",
    countryName: "Tunisia",
    alpha3Code: "TUN",
    numericCode: "788",
  },
  {
    countryCode: "TR",
    countryName: "Turkey",
    alpha3Code: "TUR",
    numericCode: "792",
  },
  {
    countryCode: "TM",
    countryName: "Turkmenistan",
    alpha3Code: "TKM",
    numericCode: "795",
  },
  {
    countryCode: "TC",
    countryName: "Turks and Caicos Islands (the)",
    alpha3Code: "TCA",
    numericCode: "796",
    alternativeNames: ["Turks and Caicos Islands"],
  },
  {
    countryCode: "TV",
    countryName: "Tuvalu",
    alpha3Code: "TUV",
    numericCode: "798",
  },
  {
    countryCode: "UG",
    countryName: "Uganda",
    alpha3Code: "UGA",
    numericCode: "800",
  },
  {
    countryCode: "UA",
    countryName: "Ukraine",
    alpha3Code: "UKR",
    numericCode: "804",
  },
  {
    countryCode: "AE",
    countryName: "United Arab Emirates (the)",
    alpha3Code: "ARE",
    numericCode: "784",
    alternativeNames: ["United Arab Emirates"],
  },
  {
    countryCode: "GB",
    countryName: "United Kingdom of Great Britain and Northern Ireland (the)",
    alpha3Code: "GBR",
    numericCode: "826",
    alternativeNames: [
      "United Kingdom",
      "United Kingdom of Great Britain and Northern Ireland",
    ],
  },
  {
    countryCode: "UM",
    countryName: "United States Minor Outlying Islands (the)",
    alpha3Code: "UMI",
    numericCode: "581",
    alternativeNames: ["United States Minor Outlying Islands"],
  },
  {
    countryCode: "US",
    countryName: "United States of America (the)",
    alpha3Code: "USA",
    numericCode: "840",
    alternativeNames: [
      "United States",
      "United States of America",
      "US",
      "USA",
    ],
  },
  {
    countryCode: "UY",
    countryName: "Uruguay",
    alpha3Code: "URY",
    numericCode: "858",
  },
  {
    countryCode: "UZ",
    countryName: "Uzbekistan",
    alpha3Code: "UZB",
    numericCode: "860",
  },
  {
    countryCode: "VU",
    countryName: "Vanuatu",
    alpha3Code: "VUT",
    numericCode: "548",
  },
  {
    countryCode: "VE",
    countryName: "Venezuela (Bolivarian Republic of)",
    alpha3Code: "VEN",
    numericCode: "862",
    alternativeNames: ["Venezuela"],
  },
  {
    countryCode: "VN",
    countryName: "Viet Nam",
    alpha3Code: "VNM",
    numericCode: "704",
    alternativeNames: ["Vietnam"],
  },
  {
    countryCode: "VG",
    countryName: "Virgin Islands (British)",
    alpha3Code: "VGB",
    numericCode: "092",
  },
  {
    countryCode: "VI",
    countryName: "Virgin Islands (U.S.)",
    alpha3Code: "VIR",
    numericCode: "850",
  },
  {
    countryCode: "WF",
    countryName: "Wallis and Futuna",
    alpha3Code: "WLF",
    numericCode: "876",
  },
  {
    countryCode: "EH",
    countryName: "Western Sahara",
    alpha3Code: "ESH",
    numericCode: "732",
  },
  {
    countryCode: "YE",
    countryName: "Yemen",
    alpha3Code: "YEM",
    numericCode: "887",
  },
  {
    countryCode: "ZM",
    countryName: "Zambia",
    alpha3Code: "ZMB",
    numericCode: "894",
  },
  {
    countryCode: "ZW",
    countryName: "Zimbabwe",
    alpha3Code: "ZWE",
    numericCode: "716",
  },
];
